name: "pipeline_pyctc_ensemble_EN"
platform: "ensemble"
max_batch_size: 32 #MAX_BATCH
input {
  name: "AUDIO_SIGNAL"
  data_type: TYPE_FP32
  dims: -1#AUDIO_LENGTH
}
input {
    name: "NUM_SAMPLES"
    data_type: TYPE_INT32
    dims: [ 1 ]
}
input {
    name: "HOTWORD_LIST"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
}
input {
    name: "HOTWORD_WEIGHT"
    data_type: TYPE_FP32
    dims: [ -1 ]
    optional: true
}

output {
  name: "TRANSCRIPTS_ASR"
  data_type: TYPE_STRING
  dims: [1]
}

output {
  name: "TRANSCRIPTS_ITN"
  data_type: TYPE_STRING
  dims: [1]
}

output {
  name: "LABELS_INTENT"
  data_type: TYPE_STRING
  dims: [1]
}

output {
  name: "JSON_ENTITY"
  data_type: TYPE_STRING
  dims: [1]
}

ensemble_scheduling {
 step [
   {
    model_name: "asr_preprocessor"
    model_version: -1
    input_map {
      key: "AUDIO_SIGNAL__0"
      value: "AUDIO_SIGNAL"
    }
    input_map {
      key: "NUM_SAMPLES__1"
      value: "NUM_SAMPLES"
    }
    output_map {
      key: "AUDIO_FEATURES__0"
      value: "audio_features"
    } 
    output_map {
      key: "NUM_TIME_STEPS__1"
      value: "NUM_TIME_STEPS"
    } 
  },
  {
    model_name: "asr_am_EN"
    model_version: -1
    input_map {
      key: "audio_signal"
      value: "audio_features"
    }
	input_map {
	    key: "length"
	    value: "NUM_TIME_STEPS"
	}
    output_map {
      key: "logprobs"
      value: "logits_am"
    }
  },
  {
    model_name: "asr_pyctc_decoder_EN"
    model_version: -1
    input_map {
      key: "LOG_PROBS"
      value: "logits_am"
    }
    input_map {
        key: "HOTWORD_LIST"
        value: "HOTWORD_LIST"
    }
    input_map {
        key: "HOTWORD_WEIGHT"
        value: "HOTWORD_WEIGHT"
    }
    output_map {
        key: "TRANSCRIPT"
        value: "TRANSCRIPTS_ASR"
    }
  },
   {
  model_name: "itn_EN"
  model_version: -1
  input_map {
   key: "INPUT_TEXT"
   value: "TRANSCRIPTS_ASR"
  }
  output_map {
   key: "OUTPUT_TEXT"
   value: "TRANSCRIPTS_ITN"
  }
 },
    {
      model_name: "intent_preprocessor"
      model_version: -1
      input_map {  
            key: "input_text"
            value: "TRANSCRIPTS_ITN"
      }
      output_map {  
            key: "input_ids"
            value: "input_ids"
      }
      output_map {  
            key: "attention_mask"
            value: "attention_mask"
      }
    },
    {
      model_name: "intent_model_onnx"
      model_version: -1
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      output_map {
      key: "logits"
      value: "logits_intent"
      }
    },
    {
      model_name: "intent_postprocessor"
      model_version: -1
      input_map {
          key: "logits"
          value: "logits_intent"
      }
      output_map {
          key: "labels"
          value: "LABELS_INTENT"
      }
    },
    {
      model_name: "entity_EN"
      model_version: -1
      input_map {
          key: "input_text"
          value: "TRANSCRIPTS_ASR"
      }
      input_map {
          key: "input_text_itn"
          value: "TRANSCRIPTS_ITN"
      }
      output_map {
          key: "entities"
          value: "JSON_ENTITY"
      }
    }
 ]
}