name: "intent_postprocessor"
backend: "python"
max_batch_size: 64
input {
    name: "logits"
    data_type: TYPE_FP32
    dims: [15]
}
  
output {
    name: "labels"
    data_type: TYPE_STRING
    dims: [ 1 ]
    reshape: { shape: [ ] }
}

instance_group {
  count: 1
  kind: KIND_CPU
}
